#ifndef PEONYBLUETOOTHPLUGIN_GLOBAL_H
#define PEONYBLUETOOTHPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEONYENGRAMPAMENUPLUGIN_LIBRARY)
#  define PEONYQTENGRAMPAMENUPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PEONYQTENGRAMPAMENUPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEONYBLUETOOTHPLUGIN_GLOBAL_H
