#ifndef PEONYQTEXTENSIONCOMPUTERVIEW_GLOBAL_H
#define PEONYQTEXTENSIONCOMPUTERVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEONYQTEXTENSIONCOMPUTERVIEW_LIBRARY)
#  define PEONYQTEXTENSIONCOMPUTERVIEW_EXPORT Q_DECL_EXPORT
#else
#  define PEONYQTEXTENSIONCOMPUTERVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // PEONYQTEXTENSIONCOMPUTERVIEW_GLOBAL_H
